name: format code

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  format_through_push:
    name: format, add, commit, push
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install packages
        run: yarn install
      - name: Set information to github 
        run: |
          git remote set-url origin https://${GITHUB_ACTOR}:${{ steps.generate_token.outputs.token }}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
      - name: Checkout pushed branch
        run: |
          git fetch
          git branch
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          git checkout $BRANCH_NAME
      - name: Format code
        run: yarn run format
      - name: Check status
        run: git status
      - name: Add changes
        run: git add .
      - name: Commit changes
        run: git commit -m "Auto commit from GitHub Actions"
      - name: Push to github
        run: |
          git push origin $BRANCH_NAME
