name: format code

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  format_through_push:
    name: format, add, commit, push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate token
        uses: actions/github-script@v4
        id: generate_token
        with:
          script: |
             if (context.payload.installation) {
              const token = github.actions.createToken({
                 installation_id: context.payload.installation.id,
                 permissions: ["write"]
              });
              console.log(token);
              core.setOutput("token", token);
             } else {
               console.log("Installation ID not found in payload");
             }
          result-encoding: string
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install packages
        run: yarn install
      - name: Set information to github 
        run: |
          git remote set-url origin https://${GITHUB_ACTOR}:${{ steps.generate_token.outputs.token }}@github.com/${GITHUB_REPOSITORY}
          git config user.name "${GITHUB_ACTOR}"
      - name: Checkout pushed branch
        run: |
          git fetch
          git branch
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          git checkout $BRANCH_NAME
      - name: Format code
        run: yarn run format
      - name: Check status
        run: git status
      - name: Add changes
        run: git add .
      - name: Commit changes
        run: git commit -m "Auto commit from GitHub Actions"
      - name: Push to github
        run: |
          git push origin $GITHUB_REF
