name: format code

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: install packages
        run: yarn install
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GITHUB_APP_ID }}
          private_key: ${{ secrets.GITHUB_PRIVATE_KEY }}
      - name: set infomation to github 
        run: |
          git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: checkout pushed branch
        run: |
          git fetch
          git branch
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          git checkout $BRANCH_NAME
      - name: format code
        run: yarn run format
      - name: check status
        run: git status
      - name: add changes
        run: git add .
      - name: commit changes
        run: git commit -m "Auto commit from GitHub Actions"
      - name: push to github
        run: |
          git push origin $BRANCH_NAME
